{
 "title": "PGDog",
 "description": "PgDog is a transaction pooler and logical replication manager that can shard PostgreSQL. Written in Rust, PgDog is fast, secure and can manage hundreds of databases and hundreds of thousands of connections.\r\n\r\npg dog",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pooler",
    "label": "Pooler",
    "query": {
     "query": "label_values(pgdog_total_sent, job)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(pgdog_total_sent{job=~\"$pooler\"},host)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(pgdog_total_sent{job=~\"$pooler\"},port)"
    }
   },
   {
    "name": "shard",
    "query": {
     "query": "label_values(pgdog_total_sent{job=~\"$pooler\"},shard)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(pgdog_total_sent{job=~\"$pooler\"},role)"
    }
   },
   {
    "name": "database",
    "query": {
     "query": "label_values(pgdog_total_sent{job=~\"$pooler\"},database)"
    }
   },
   {
    "name": "user",
    "query": {
     "query": "label_values(pgdog_total_sent{job=~\"$pooler\"},user)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clients Total",
   "type": "timeseries",
   "description": "Total number of connected clients.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgdog_clients{job=~\"$pooler\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients Waiting",
   "type": "timeseries",
   "description": "Clients waiting for a connection from a pool.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgdog_cl_waiting{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Servers Active",
   "type": "timeseries",
   "description": "Servers currently serving client requests.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgdog_sv_active{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Servers Idle",
   "type": "timeseries",
   "description": "Servers available for clients to use.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgdog_sv_idle{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Servers Idle In Transaction",
   "type": "timeseries",
   "description": "Servers currently idle in transaction.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgdog_sv_idle_xact{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  { "title": "Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Connection Max Wait Time",
   "type": "timeseries",
   "description": "How long clients have been waiting for a connection.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max (pgdog_maxwait{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Connection Errors Rate",
   "type": "timeseries",
   "description": "Errors that connections in the pool have experienced.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(pgdog_errors{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}[$__rate_interval])) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Connection Out Of Sync Rate",
   "type": "timeseries",
   "description": "Connections that have been returned to the pool in a broken state.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(pgdog_out_of_sync{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}[$__rate_interval])) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  { "title": "Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Transactions Rate",
   "type": "timeseries",
   "description": "Total number of executed transactions.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(pgdog_total_xact_count{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}[$__rate_interval])) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Two-Phase Commit Transactions Rate",
   "type": "timeseries",
   "description": "Total number of executed two-phase commit transactions.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(pgdog_total_xact_2pc_count{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}[$__rate_interval])) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Transactions Executing Time Rate",
   "type": "timeseries",
   "description": "Total time spent executing transactions.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "avg (rate(pgdog_total_xact_time{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}[$__rate_interval])) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Average Transactions Count",
   "type": "timeseries",
   "description": "Average number of executed transactions per statistics period.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgdog_avg_xact_count{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Average Two-Phase Commit Transactions Count",
   "type": "timeseries",
   "description": "Average number of executed two-phase commit transactions per statistics period.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgdog_avg_xact_2pc_count{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Average Time Spent Executing Transactions",
   "type": "timeseries",
   "description": "Average time spent executing transactions.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "avg (pgdog_avg_xact_time{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "description": "Total number of executed queries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(pgdog_total_query_count{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}[$__rate_interval])) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Query Executing Time Rate",
   "type": "timeseries",
   "description": "Total time spent executing queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "avg (rate(pgdog_total_query_time{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}[$__rate_interval])) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Average Query Count",
   "type": "timeseries",
   "description": "Average number of executed queries per statistics period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgdog_avg_query_count{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Average Query Executing Time",
   "type": "timeseries",
   "description": "Average time spent executing queries.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "avg (pgdog_avg_query_time{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Query Cache Size",
   "type": "timeseries",
   "description": "Number of queries in the cache.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgdog_query_cache_size{job=~\"$pooler\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Cache Rate",
   "type": "timeseries",
   "description": "HIT - Queries already present in the query cache.\n\nMISS - New queries added to the query cache.\n\nDIRECT - Queries sent directly to a single shard.\n\nCROSS - Queries sent to multiple or all shards.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(pgdog_query_cache_hits{job=~\"$pooler\"}[$__rate_interval])) by (instance)",
     "legendFormat": "HIT {{instance}}"
    },
    {
     "expr": "sum (rate(pgdog_query_cache_misses{job=~\"$pooler\"}[$__rate_interval])) by (instance)",
     "legendFormat": "MISS {{instance}}"
    },
    {
     "expr": "sum (rate(pgdog_query_cache_direct{job=~\"$pooler\"}[$__rate_interval])) by (instance)",
     "legendFormat": "DIRECT {{instance}}"
    },
    {
     "expr": "sum (rate(pgdog_query_cache_cross{job=~\"$pooler\"}[$__rate_interval])) by (instance)",
     "legendFormat": "CROSS {{instance}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Traffic Received Rate",
   "type": "timeseries",
   "description": "Total number of bytes received.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (rate(pgdog_total_received{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}[$__rate_interval])) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Traffic Sent Rate",
   "type": "timeseries",
   "description": "Total number of bytes sent.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (rate(pgdog_total_sent{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}[$__rate_interval])) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Average Traffic Received",
   "type": "timeseries",
   "description": "Average number of bytes received.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (pgdog_avg_received{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Average Traffic Sent",
   "type": "timeseries",
   "description": "Average number of bytes sent.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (pgdog_avg_sent{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  { "title": "Prepared Statement", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Prepared Statements Memory Used",
   "type": "timeseries",
   "description": "Number of bytes used for the prepared statements cache.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (pgdog_prepared_statements_memory_used{job=~\"$pooler\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prepared Statements Eviction Rate",
   "type": "timeseries",
   "description": "Total number of prepared statements closed because of cache evictions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(pgdog_total_prepared_evictions{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}[$__rate_interval])) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Prepared Statements Count",
   "type": "timeseries",
   "description": "Number of prepared statements in the cache.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgdog_prepared_statements{job=~\"$pooler\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Prepared Statements Eviction Count",
   "type": "timeseries",
   "description": "Average number of prepared statements closed because of cache evictions.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgdog_avg_prepared_evictions{job=~\"$pooler\", host=~\"$host\", port=~\"$port\", shard=\"$shard\", role=~\"$role\", database=~\"$database\", user=~\"$user\"}) by (host, port, shard, role, database, user)",
     "legendFormat": "{{host}}:{{port}} shard:{{shard}} role:{{role}} db:{{database}} user:{{user}}"
    }
   ]
  },
  { "title": "Mirror", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Mirror Rate",
   "type": "timeseries",
   "description": "TOTAL - Total number of requests considered for mirroring.\n\nMIRRORED - Total number of requests successfully mirrored.\n\nDROPPED - Total number of requests dropped due to exposure settings.\n\nERROR - Total number of mirror requests that encountered errors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(pgdog_mirror_total_count{job=~\"$pooler\", database=~\"$database\", user=~\"$user\"}[$__rate_interval])) by (instance, database, user)",
     "legendFormat": "TOTAL {{instance}} db:{{database}} user:{{user}}"
    },
    {
     "expr": "sum (rate(pgdog_mirror_mirrored_count{job=~\"$pooler\", database=~\"$database\", user=~\"$user\"}[$__rate_interval])) by (instance, database, user)",
     "legendFormat": "MIRRORED {{instance}} db:{{database}} user:{{user}}"
    },
    {
     "expr": "sum (rate(pgdog_mirror_dropped_count{job=~\"$pooler\", database=~\"$database\", user=~\"$user\"}[$__rate_interval])) by (instance, database, user)",
     "legendFormat": "DROPPED {{instance}} db:{{database}} user:{{user}}"
    },
    {
     "expr": "sum (rate(pgdog_mirror_error_count{job=~\"$pooler\", database=~\"$database\", user=~\"$user\"}[$__rate_interval])) by (instance, database, user)",
     "legendFormat": "ERROR {{instance}} db:{{database}} user:{{user}}"
    }
   ]
  },
  {
   "title": "Mirror Queue Size",
   "type": "timeseries",
   "description": "Current number of transactions in the mirror queue.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (pgdog_mirror_queue_length{job=~\"$pooler\", database=~\"$database\", user=~\"$user\"}) by (instance, database, user)",
     "legendFormat": "{{instance}} db:{{database}} user:{{user}}"
    }
   ]
  }
 ]
}