package generate

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"github.com/grafana/grafana-foundation-sdk/go/dashboardv2"
	"gopkg.in/yaml.v3"

	"github.com/duynhlab/grafana-dashboards/internal/alerts"
	"github.com/duynhlab/grafana-dashboards/internal/registry"
)

const (
	generatedHeader     = "# Code generated by go run ./cmd/generate; DO NOT EDIT.\n"
	defaultOCIReference = "ghcr.io/duynhlab/grafana-dashboards:latest"
)

// ociReferencePattern mirrors the validation the Grafana Operator applies to
// spec.oci.reference. It rejects a port in the registry host, so an in-cluster
// registry must be reachable on port 80 or 443.
var ociReferencePattern = regexp.MustCompile(`^[^:@]+(:[^:@/]+|@sha256:[a-fA-F0-9]{64})$`)

type Generator struct {
	root            string
	dashboards      []registry.DashboardDefinition
	alerts          []alerts.Rule
	ociReference    string
	ociPullSecret   string
	ociInsecureHTTP bool
}

func New(root string, dashboards []registry.DashboardDefinition, alertRules []alerts.Rule) (*Generator, error) {
	if strings.TrimSpace(root) == "" {
		return nil, errors.New("output root must not be empty")
	}
	reference := strings.TrimSpace(os.Getenv("OCI_REFERENCE"))
	if reference == "" {
		reference = defaultOCIReference
	}
	if !ociReferencePattern.MatchString(reference) {
		return nil, fmt.Errorf("OCI reference %q is rejected by the GrafanaDashboard CRD: the registry host must not carry a port", reference)
	}
	return &Generator{
		root:            root,
		dashboards:      dashboards,
		alerts:          alertRules,
		ociReference:    reference,
		ociPullSecret:   strings.TrimSpace(os.Getenv("OCI_PULL_SECRET")),
		ociInsecureHTTP: os.Getenv("OCI_INSECURE_PLAIN_HTTP") == "true",
	}, nil
}

func Run() error {
	generator, err := New(".", registry.Dashboards, registry.Alerts)
	if err != nil {
		return err
	}
	return generator.Run()
}

func (g *Generator) Run() error {
	if err := g.prepareOutput(); err != nil {
		return err
	}

	for _, definition := range g.dashboards {
		if err := g.writeDashboard(definition); err != nil {
			return fmt.Errorf("dashboard %s: %w", definition.UID, err)
		}
	}
	if err := g.writeAlertGroups(); err != nil {
		return err
	}
	if err := g.writeGrafanaFolders(); err != nil {
		return err
	}
	return g.writeKustomization()
}

func (g *Generator) prepareOutput() error {
	for _, directory := range []string{
		g.path("generated", "dashboards"),
		g.path("generated", "alerts"),
		g.path("deploy", "manifests"),
	} {
		if err := os.RemoveAll(directory); err != nil {
			return fmt.Errorf("clean %s: %w", directory, err)
		}
		if err := os.MkdirAll(directory, 0o755); err != nil {
			return fmt.Errorf("create %s: %w", directory, err)
		}
	}
	return nil
}

func (g *Generator) writeDashboard(definition registry.DashboardDefinition) error {
	if strings.TrimSpace(definition.Domain) == "" {
		return errors.New("domain must not be empty: it is the directory segment under generated/dashboards and the prefix of spec.oci.path")
	}

	manifest, err := dashboardv2.Manifest(definition.UID, definition.Build()).Build()
	if err != nil {
		return err
	}

	directory := g.path("generated", "dashboards", definition.Domain)
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", directory, err)
	}
	if err := writeJSON(filepath.Join(directory, definition.UID+".manifest.json"), manifest); err != nil {
		return err
	}
	if err := writeJSON(filepath.Join(directory, definition.UID+".spec.json"), manifest.Spec); err != nil {
		return err
	}
	return g.writeGrafanaDashboardCR(definition)
}

// dashboardSpecPath is the artifact-relative location of a dashboard's spec
// JSON. It is both the path inside the OCI artifact, as recorded in the layer's
// title annotation by oras, and the value of spec.oci.path that the Grafana
// Operator matches against it. Always slash-separated, never filepath.Join.
func dashboardSpecPath(definition registry.DashboardDefinition) string {
	return path.Join(definition.Domain, definition.UID+".spec.json")
}

func writeJSON(path string, value any) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0o644)
}

func writeYAML(path string, value any) error {
	data, err := yaml.Marshal(value)
	if err != nil {
		return err
	}
	return os.WriteFile(path, append([]byte(generatedHeader), data...), 0o644)
}

func (g *Generator) writeGrafanaDashboardCR(definition registry.DashboardDefinition) error {
	oci := map[string]any{
		"reference": g.ociReference,
		"path":      dashboardSpecPath(definition),
	}
	if g.ociInsecureHTTP {
		oci["insecurePlainHTTP"] = true
	}
	if g.ociPullSecret != "" {
		oci["pullSecretRef"] = map[string]string{"name": g.ociPullSecret}
	}
	document := map[string]any{
		"apiVersion": "grafana.integreatly.org/v1beta1",
		"kind":       "GrafanaDashboard",
		"metadata":   metadata(definition.UID),
		"spec": map[string]any{
			"instanceSelector": instanceSelector(),
			"folderRef":        folderSlug(definition.Folder),
			"oci":              oci,
		},
	}
	return writeYAML(g.path("deploy", "manifests", "grafanadashboard-"+definition.UID+".yaml"), document)
}

func (g *Generator) writeGrafanaFolders() error {
	for _, folder := range folders(g.dashboards, g.alerts) {
		slug := folderSlug(folder)
		document := map[string]any{
			"apiVersion": "grafana.integreatly.org/v1beta1",
			"kind":       "GrafanaFolder",
			"metadata":   metadata(slug),
			"spec": map[string]any{
				"instanceSelector": instanceSelector(),
				"title":            folder,
				"uid":              slug,
			},
		}
		if err := writeYAML(g.path("deploy", "manifests", "grafanafolder-"+slug+".yaml"), document); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) writeAlertGroups() error {
	groups := map[string][]alerts.Rule{}
	for _, rule := range g.alerts {
		if strings.TrimSpace(rule.Domain) == "" {
			return fmt.Errorf("alert %s: domain must not be empty: it is the directory segment under generated/alerts", rule.UID)
		}
		directory := g.path("generated", "alerts", rule.Domain)
		if err := os.MkdirAll(directory, 0o755); err != nil {
			return fmt.Errorf("create %s: %w", directory, err)
		}
		if err := writeJSON(filepath.Join(directory, rule.UID+".json"), rule); err != nil {
			return err
		}
		groups[rule.Group] = append(groups[rule.Group], rule)
	}

	names := make([]string, 0, len(groups))
	for name := range groups {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, group := range names {
		rules := groups[group]
		renderedRules := make([]map[string]any, 0, len(rules))
		for _, rule := range rules {
			renderedRules = append(renderedRules, grafanaAlertRule(rule))
		}
		document := map[string]any{
			"apiVersion": "grafana.integreatly.org/v1beta1",
			"kind":       "GrafanaAlertRuleGroup",
			"metadata":   metadata(group),
			"spec": map[string]any{
				"name":             group,
				"folderRef":        folderSlug(rules[0].Folder),
				"interval":         "1m",
				"instanceSelector": instanceSelector(),
				"rules":            renderedRules,
			},
		}
		if err := writeYAML(g.path("deploy", "manifests", "grafanaalertrulegroup-"+group+".yaml"), document); err != nil {
			return err
		}
	}
	return nil
}

func grafanaAlertRule(rule alerts.Rule) map[string]any {
	return map[string]any{
		"uid":          rule.UID,
		"title":        rule.Title,
		"condition":    "B",
		"for":          rule.For,
		"noDataState":  "NoData",
		"execErrState": "Error",
		"labels":       rule.Labels,
		"annotations":  rule.Annotations,
		"data": []map[string]any{
			{
				"refId":             "A",
				"datasourceUid":     "prometheus",
				"relativeTimeRange": map[string]any{"from": 600, "to": 0},
				"model": map[string]any{
					"datasource": map[string]string{"type": "prometheus", "uid": "prometheus"},
					"editorMode": "code",
					"expr":       rule.Expr,
					"instant":    true,
					"refId":      "A",
				},
			},
			{
				"refId":         "B",
				"datasourceUid": "__expr__",
				"model": map[string]any{
					"datasource": map[string]string{"type": "__expr__", "uid": "__expr__"},
					"type":       "threshold",
					"expression": "A",
					"refId":      "B",
					"conditions": []map[string]any{{
						"evaluator": map[string]any{"type": "gt", "params": []float64{rule.Threshold}},
						"operator":  map[string]any{"type": "and"},
						"reducer":   map[string]any{"type": "last", "params": []any{}},
						"type":      "query",
					}},
				},
			},
		},
	}
}

func (g *Generator) writeKustomization() error {
	resources := make([]string, 0, len(g.dashboards)+len(g.alerts))
	for _, folder := range folders(g.dashboards, g.alerts) {
		resources = append(resources, "manifests/grafanafolder-"+folderSlug(folder)+".yaml")
	}
	for _, definition := range g.dashboards {
		resources = append(resources, "manifests/grafanadashboard-"+definition.UID+".yaml")
	}
	groups := map[string]struct{}{}
	for _, rule := range g.alerts {
		groups[rule.Group] = struct{}{}
	}
	groupNames := make([]string, 0, len(groups))
	for group := range groups {
		groupNames = append(groupNames, group)
	}
	sort.Strings(groupNames)
	for _, group := range groupNames {
		resources = append(resources, "manifests/grafanaalertrulegroup-"+group+".yaml")
	}

	document := map[string]any{
		"apiVersion": "kustomize.config.k8s.io/v1beta1",
		"kind":       "Kustomization",
		"namespace":  "grafana-operator",
		"resources":  resources,
	}
	return writeYAML(g.path("deploy", "kustomization.yaml"), document)
}

func folders(dashboards []registry.DashboardDefinition, alertRules []alerts.Rule) []string {
	seen := map[string]struct{}{}
	output := make([]string, 0)
	add := func(folder string) {
		if folder == "" {
			return
		}
		if _, exists := seen[folder]; exists {
			return
		}
		seen[folder] = struct{}{}
		output = append(output, folder)
	}
	for _, dashboard := range dashboards {
		add(dashboard.Folder)
	}
	for _, rule := range alertRules {
		add(rule.Folder)
	}
	return output
}

func metadata(name string) map[string]any {
	return map[string]any{
		"name": name,
		"labels": map[string]string{
			"app.kubernetes.io/part-of": "grafana-dashboards-as-code",
		},
	}
}

func instanceSelector() map[string]any {
	return map[string]any{"matchLabels": map[string]string{"dashboards": "grafana"}}
}

func folderSlug(folder string) string {
	var builder strings.Builder
	lastDash := false
	for _, character := range strings.ToLower(strings.TrimSpace(folder)) {
		if unicode.IsLetter(character) || unicode.IsDigit(character) {
			builder.WriteRune(character)
			lastDash = false
			continue
		}
		if !lastDash && builder.Len() > 0 {
			builder.WriteByte('-')
			lastDash = true
		}
	}
	return strings.Trim(builder.String(), "-")
}

func (g *Generator) path(parts ...string) string {
	return filepath.Join(append([]string{g.root}, parts...)...)
}
