package generate

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/grafana/grafana-foundation-sdk/go/dashboardv2"
	"gopkg.in/yaml.v3"

	"github.com/duynhlab/grafana-dashboards/internal/alerts"
	"github.com/duynhlab/grafana-dashboards/internal/registry"
)

const (
	generatedHeader = "# Code generated by go run ./cmd/generate; DO NOT EDIT.\n"

	// operatorAPIVersion is the Grafana Operator's own CRD API. It is v1beta1 for
	// every kind the operator ships and is not the dashboard schema version.
	operatorAPIVersion = "grafana.integreatly.org/v1beta1"

	// tenantNamespace is Grafana's own tenant namespace, which is where an App
	// Platform resource lives. It is not the namespace the operator watches: the
	// CR sits in the operator's namespace and the object it carries sits here.
	tenantNamespace = "default"

	// folderAnnotation carries the *UID* of the owning folder, which is the
	// folder object's inner metadata.name, not the "-folder" name of the CR that
	// wraps it.
	folderAnnotation = "grafana.app/folder"

	// folderAPIVersion is a different API group from the dashboard schema.
	folderAPIVersion = "folder.grafana.app/v1"

	resyncPeriod = "10m"

	// The two delivery waves. A dashboard cannot be applied before the folder it
	// annotates exists, and the alert groups reference the same folder by UID, so
	// everything except the folders belongs to the second wave.
	waveFolders    = "folders"
	waveDashboards = "dashboards"
)

type Generator struct {
	root       string
	dashboards []registry.DashboardDefinition
	alerts     []alerts.Rule
}

func New(root string, dashboards []registry.DashboardDefinition, alertRules []alerts.Rule) (*Generator, error) {
	if strings.TrimSpace(root) == "" {
		return nil, errors.New("output root must not be empty")
	}
	return &Generator{
		root:       root,
		dashboards: dashboards,
		alerts:     alertRules,
	}, nil
}

func Run() error {
	generator, err := New(".", registry.Dashboards, registry.Alerts)
	if err != nil {
		return err
	}
	return generator.Run()
}

func (g *Generator) Run() error {
	if err := g.prepareOutput(); err != nil {
		return err
	}

	for _, definition := range g.dashboards {
		if err := g.writeDashboard(definition); err != nil {
			return fmt.Errorf("dashboard %s: %w", definition.UID, err)
		}
	}
	if err := g.writeAlertGroups(); err != nil {
		return err
	}
	if err := g.writeFolders(); err != nil {
		return err
	}
	return g.writeKustomization()
}

func (g *Generator) prepareOutput() error {
	for _, directory := range []string{
		g.path("generated", "dashboards"),
		g.path("generated", "alerts"),
		g.path("deploy", "folders"),
		g.path("deploy", "dashboards"),
	} {
		if err := os.RemoveAll(directory); err != nil {
			return fmt.Errorf("clean %s: %w", directory, err)
		}
		if err := os.MkdirAll(directory, 0o755); err != nil {
			return fmt.Errorf("create %s: %w", directory, err)
		}
	}
	return nil
}

func (g *Generator) writeDashboard(definition registry.DashboardDefinition) error {
	if strings.TrimSpace(definition.Domain) == "" {
		return errors.New("domain must not be empty: it is the directory segment under generated/dashboards")
	}

	manifest, err := dashboardv2.Manifest(definition.UID, definition.Build()).Build()
	if err != nil {
		return err
	}

	// The App Platform object carries its own namespace and its folder. Setting
	// them here rather than only on the CR keeps the generated manifest.json
	// byte-identical to what is applied.
	namespace := tenantNamespace
	manifest.Metadata.Namespace = &namespace
	manifest.Metadata.Annotations = map[string]string{
		folderAnnotation: folderSlug(definition.Folder),
	}

	directory := g.path("generated", "dashboards", definition.Domain)
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", directory, err)
	}
	if err := writeJSON(filepath.Join(directory, definition.UID+".manifest.json"), manifest); err != nil {
		return err
	}
	if err := writeJSON(filepath.Join(directory, definition.UID+".spec.json"), manifest.Spec); err != nil {
		return err
	}

	template, err := toDocument(manifest)
	if err != nil {
		return fmt.Errorf("render template: %w", err)
	}
	return g.writeManifestCR(waveDashboards, dashboardCRName(definition.UID), template)
}

func writeJSON(path string, value any) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(data, '\n'), 0o644)
}

func writeYAML(path string, value any) error {
	data, err := yaml.Marshal(value)
	if err != nil {
		return err
	}
	return os.WriteFile(path, append([]byte(generatedHeader), data...), 0o644)
}

// toDocument re-encodes a value through JSON so the YAML document uses the JSON
// field names. yaml.Marshal reads yaml tags and lowercases everything else, so
// marshalling an SDK struct directly would emit a spec Grafana cannot read.
func toDocument(value any) (map[string]any, error) {
	data, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	var document map[string]any
	if err := json.Unmarshal(data, &document); err != nil {
		return nil, err
	}
	return document, nil
}

// writeManifestCR wraps an App Platform object in the only operator resource
// that can carry one.
//
// GrafanaDashboard posts through the legacy /api/dashboards/db envelope and
// cannot carry a dashboard.grafana.app/v2 payload at all: Grafana answers 400
// on the bare spec ("dashboard appears to be in v2 format") and 400 again on
// the wrapped object ("must not include an id on the root element"), the second
// being unfixable from here because the operator's content resolver injects the
// id. GrafanaManifest applies through a discovery-based dynamic client against
// /apis instead, so it speaks the same protocol as the schema.
//
// The trade is that GrafanaManifest has no content sources at all - no oci, no
// url, no configMapRef - so the object is inlined and bounded by the etcd
// object limit near 1 MiB.
func (g *Generator) writeManifestCR(wave, name string, template map[string]any) error {
	document := map[string]any{
		"apiVersion": operatorAPIVersion,
		"kind":       "GrafanaManifest",
		"metadata":   metadata(name),
		"spec": map[string]any{
			"instanceSelector": instanceSelector(),
			"resyncPeriod":     resyncPeriod,
			"template":         template,
		},
	}
	return writeYAML(g.path("deploy", wave, "grafanamanifest-"+name+".yaml"), document)
}

// dashboardCRName and folderCRName keep the two object names apart. A folder's
// CR is suffixed so it cannot collide with a dashboard of the same slug, while
// the folder UID the dashboards annotate stays unsuffixed.
func dashboardCRName(uid string) string { return uid }

func folderCRName(slug string) string { return slug + "-folder" }

func (g *Generator) writeFolders() error {
	for _, folder := range folders(g.dashboards, g.alerts) {
		slug := folderSlug(folder)
		template := map[string]any{
			"apiVersion": folderAPIVersion,
			"kind":       "Folder",
			"metadata": map[string]any{
				"name":      slug,
				"namespace": tenantNamespace,
			},
			"spec": map[string]any{"title": folder},
		}
		if err := g.writeManifestCR(waveFolders, folderCRName(slug), template); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) writeAlertGroups() error {
	groups := map[string][]alerts.Rule{}
	for _, rule := range g.alerts {
		if strings.TrimSpace(rule.Domain) == "" {
			return fmt.Errorf("alert %s: domain must not be empty: it is the directory segment under generated/alerts", rule.UID)
		}
		directory := g.path("generated", "alerts", rule.Domain)
		if err := os.MkdirAll(directory, 0o755); err != nil {
			return fmt.Errorf("create %s: %w", directory, err)
		}
		if err := writeJSON(filepath.Join(directory, rule.UID+".json"), rule); err != nil {
			return err
		}
		groups[rule.Group] = append(groups[rule.Group], rule)
	}

	names := make([]string, 0, len(groups))
	for name := range groups {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, group := range names {
		rules := groups[group]
		renderedRules := make([]map[string]any, 0, len(rules))
		for _, rule := range rules {
			renderedRules = append(renderedRules, grafanaAlertRule(rule))
		}
		document := map[string]any{
			"apiVersion": "grafana.integreatly.org/v1beta1",
			"kind":       "GrafanaAlertRuleGroup",
			"metadata":   metadata(group),
			"spec": map[string]any{
				"name":             group,
				"folderUID":        folderSlug(rules[0].Folder),
				"interval":         "1m",
				"instanceSelector": instanceSelector(),
				"rules":            renderedRules,
			},
		}
		if err := writeYAML(g.path("deploy", waveDashboards, "grafanaalertrulegroup-"+group+".yaml"), document); err != nil {
			return err
		}
	}
	return nil
}

func grafanaAlertRule(rule alerts.Rule) map[string]any {
	return map[string]any{
		"uid":          rule.UID,
		"title":        rule.Title,
		"condition":    "B",
		"for":          rule.For,
		"noDataState":  "NoData",
		"execErrState": "Error",
		"labels":       rule.Labels,
		"annotations":  rule.Annotations,
		"data": []map[string]any{
			{
				"refId":             "A",
				"datasourceUid":     "prometheus",
				"relativeTimeRange": map[string]any{"from": 600, "to": 0},
				"model": map[string]any{
					"datasource": map[string]string{"type": "prometheus", "uid": "prometheus"},
					"editorMode": "code",
					"expr":       rule.Expr,
					"instant":    true,
					"refId":      "A",
				},
			},
			{
				"refId":         "B",
				"datasourceUid": "__expr__",
				"model": map[string]any{
					"datasource": map[string]string{"type": "__expr__", "uid": "__expr__"},
					"type":       "threshold",
					"expression": "A",
					"refId":      "B",
					"conditions": []map[string]any{{
						"evaluator": map[string]any{"type": "gt", "params": []float64{rule.Threshold}},
						"operator":  map[string]any{"type": "and"},
						"reducer":   map[string]any{"type": "last", "params": []any{}},
						"type":      "query",
					}},
				},
			},
		},
	}
}

// writeKustomization emits one overlay per delivery wave plus a flat root that
// aggregates both. The root applies everything at once and is what make
// validate and the Kind e2e use, where apply order does not matter because
// nothing is racing.
//
// The waves exist for the ordering constraint: a board whose grafana.app/folder
// names a folder that does not exist yet fails outright with
// `folders.folder.grafana.app "<uid>" not found`, then waits for the operator's
// next resync - long enough that a Flux wave times out red rather than riding
// it out. Listing the folder first inside one kustomization is not a guarantee;
// kustomize ordering is not apply ordering for independent controllers. Only
// dependsOn between two Flux Kustomizations is, which is why a consumer points
// one wave at ./deploy/folders and the next at ./deploy/dashboards.
//
// Such a consumer also needs healthCheckExprs: GrafanaManifest reports
// ManifestSynchronized, not the Ready condition kstatus expects.
func (g *Generator) writeKustomization() error {
	folderResources := make([]string, 0, len(g.dashboards))
	for _, folder := range folders(g.dashboards, g.alerts) {
		folderResources = append(folderResources, manifestFile(folderCRName(folderSlug(folder))))
	}

	dashboardResources := make([]string, 0, len(g.dashboards)+len(g.alerts))
	for _, definition := range g.dashboards {
		dashboardResources = append(dashboardResources, manifestFile(dashboardCRName(definition.UID)))
	}
	for _, group := range alertGroupNames(g.alerts) {
		dashboardResources = append(dashboardResources, "grafanaalertrulegroup-"+group+".yaml")
	}

	for wave, resources := range map[string][]string{
		waveFolders:    folderResources,
		waveDashboards: dashboardResources,
	} {
		if err := writeYAML(g.path("deploy", wave, "kustomization.yaml"), kustomization(resources)); err != nil {
			return err
		}
	}

	return writeYAML(g.path("deploy", "kustomization.yaml"), kustomization([]string{waveFolders, waveDashboards}))
}

func manifestFile(name string) string {
	return "grafanamanifest-" + name + ".yaml"
}

func kustomization(resources []string) map[string]any {
	return map[string]any{
		"apiVersion": "kustomize.config.k8s.io/v1beta1",
		"kind":       "Kustomization",
		"namespace":  "grafana-operator",
		"resources":  resources,
	}
}

func alertGroupNames(rules []alerts.Rule) []string {
	groups := map[string]struct{}{}
	for _, rule := range rules {
		groups[rule.Group] = struct{}{}
	}
	names := make([]string, 0, len(groups))
	for group := range groups {
		names = append(names, group)
	}
	sort.Strings(names)
	return names
}

func folders(dashboards []registry.DashboardDefinition, alertRules []alerts.Rule) []string {
	seen := map[string]struct{}{}
	output := make([]string, 0)
	add := func(folder string) {
		if folder == "" {
			return
		}
		if _, exists := seen[folder]; exists {
			return
		}
		seen[folder] = struct{}{}
		output = append(output, folder)
	}
	for _, dashboard := range dashboards {
		add(dashboard.Folder)
	}
	for _, rule := range alertRules {
		add(rule.Folder)
	}
	return output
}

func metadata(name string) map[string]any {
	return map[string]any{
		"name": name,
		"labels": map[string]string{
			"app.kubernetes.io/part-of": "grafana-dashboards-as-code",
		},
	}
}

func instanceSelector() map[string]any {
	return map[string]any{"matchLabels": map[string]string{"dashboards": "grafana"}}
}

func folderSlug(folder string) string {
	var builder strings.Builder
	lastDash := false
	for _, character := range strings.ToLower(strings.TrimSpace(folder)) {
		if unicode.IsLetter(character) || unicode.IsDigit(character) {
			builder.WriteRune(character)
			lastDash = false
			continue
		}
		if !lastDash && builder.Len() > 0 {
			builder.WriteByte('-')
			lastDash = true
		}
	}
	return strings.Trim(builder.String(), "-")
}

func (g *Generator) path(parts ...string) string {
	return filepath.Join(append([]string{g.root}, parts...)...)
}
